Presupuesto/Controllers/TiposCuentasController.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Presupuesto.Filters;
using Presupuesto.Infraestructure;
using Presupuesto.Models;
using Presupuesto.Services;

namespace Presupuesto.Controllers
{
    public class TiposCuentasController : Controller
    {

        #region Codigo_Temporal

        private readonly string connectionString;
        private readonly ITiposCuentasServices _tiposCuentaServices;
        private readonly IUsuariosServices _usuariosServices;

        #endregion

        public TiposCuentasController(ITiposCuentasServices tiposCuentaServices, IConfiguration configuration, IUsuariosServices usuariosServices)
        {
            connectionString = configuration.GetConnectionString("DefaultConnection");
            _tiposCuentaServices = tiposCuentaServices;
            _usuariosServices = usuariosServices;
        }

        [ServiceFilter(typeof(GlobalExceptionFilter))]
        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TipoCuenta tipoCuenta)
        {
            if(ModelState.IsValid)
            {
                return View(tipoCuenta);
            }
            var ExistAccount = await
                _tiposCuentaServices.Existe(tipoCuenta.Nombre, tipoCuenta.UsuarioId);
            if(ExistAccount) 
            {
                ModelState.AddModelError(nameof(tipoCuenta.Nombre),
                    $"El nombre {tipoCuenta} ya existe");
                return View(tipoCuenta);
            }
            tipoCuenta.UsuarioId = _usuariosServices.ObtenerUsuarioId();
            //return View(tipoCuenta);
            await _tiposCuentaServices.CrearAsync(tipoCuenta);

            return RedirectToAction("ObtenerCuentas");
            //Hardcodeamos el usuario con su Id
        }

        [HttpGet]
        public async Task<IActionResult> VerificarExisteTipoCuenta(string nombre)
        {
            var usuarioId = _usuariosServices.ObtenerUsuarioId();
            var Exist = await _tiposCuentaServices.Existe(nombre, usuarioId);
            if (Exist)
            {
                return Json($"El nombre {nombre} ya existe");
            }
            return Json(true);
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = _usuariosServices.ObtenerUsuarioId();
            var tiposCuentas = await _tiposCuentaServices.Obtener(usuarioId);
            return View(tiposCuentas);
        }

        [HttpGet]
        public async Task<IActionResult> ObtenerCuentas()
        {
            return View();
        }

        [HttpGet]
        [ServiceFilter(typeof(GlobalExceptionFilter))]
        public async Task<ActionResult> Editar(int id)
        {
            var usuarioid = _usuariosServices.ObtenerUsuarioId();
            var tipoCuenta = await _tiposCuentaServices.ObtenerPorId(id, usuarioid);
            if (tipoCuenta is null)
            {
                RedirectToAction("NoEncontrado", "Home");
            }
            return View(tipoCuenta);
        }

        [HttpPost]
        [ServiceFilter(typeof(GlobalExceptionFilter))]
        public async Task<IActionResult> Editar(TipoCuenta tipoCuenta)
        {
            var usuarioId = _usuariosServices.ObtenerUsuarioId();
            var tipoCuentaExiste = await _tiposCuentaServices.ObtenerPorId(tipoCuenta.Id, usuarioId);
            if (tipoCuentaExiste is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await _tiposCuentaServices.Actualizar(tipoCuenta);
            return RedirectToAction("ObtenerCuentas");
        }

        [ServiceFilter(typeof(GlobalExceptionFilter))]
        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = _usuariosServices.ObtenerUsuarioId();
            var tipoCuenta = await _tiposCuentaServices.ObtenerPorId(id, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(tipoCuenta);
        }

        [HttpPost]
        [ServiceFilter(typeof(GlobalExceptionFilter))]
        public async Task<IActionResult> BorrarTipoCuenta(int id)
        {
            var usuarioId = _usuariosServices.ObtenerUsuarioId();
            var tipoCuenta = await _tiposCuentaServices.ObtenerPorId(id, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado" , "Home");
            }
            await _tiposCuentaServices.Borrar(id);
            return RedirectToAction("ObtenerCuentas");
        }


        [HttpGet]
        public async Task<ActionResult<PagedResults<TipoCuenta>>> GetTipoCuentas(int start, int length, int draw)
        {
            try
            {
                var pageNumber = start / length + 1;
                var pageSize = length;

                var result = await _tiposCuentaServices.ObtenerTodos(pageNumber, pageSize, draw);

                return Json(new
                {
                    draw,
                    recordsTotal = result.TotalItems,
                    recordsFiltered = result.TotalItems,
                    data = result.Items
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error interno del servidor: {ex.Message}");
            }
        }

    }
}

Presupuesto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Presupuesto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presupuesto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
</head>
<body>
 <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Presupuesto</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TiposCuentas" asp-action="ObtenerCuentas">Paginación</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header> 

    <div id="sidebar">
        <div class="toggle-btn">
            <span>&#9776</span>
        </div>
        <ul>
            <li>
                <img src="img/img.jpg" alt="Logo Fazt" class="logo">
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-area="" asp-controller="TiposCuentas" asp-action="ObtenerCuentas">Paginación</a>
            </li>
        </ul>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Presupuesto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.2/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.0.2/js/dataTables.bootstrap5.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>